print("Give me a word!")
input()
print("Give me another word!")
input()
print()
print("Great, now your favourite number?")
input()
print()
print("And your second favourite number...")
input()
print()
print("Whew Wasn't that fun?")
