print("Please enter the following information so I can sell it for a profit!")
print()

fname = input("First name: ")
lname = input("Last name: ")
grade = input("Grade: ")
id = input("Studet ID: ")
login = input("Login: ")
average = input("Average: ")

print("Your information:")
print(f"Login:{login}")
print(f"IF: {id}")
print(f"Name: {lname}, {fname}")
print(f"Average: {average}%")
print(f"Grade: {grade}")
